export const initialProgressData = [
  {
    conceptId: 'concept-unity-profiler-cpu',
    subjectId: 'xr-qa',
    status: 'learning',
    progress: 75,
    understandingLevel: 'intermediate',
    lastStudiedDate: '2026-09-24T14:30:00.000Z',
    lastPracticedDate: '2026-09-24T16:00:00.000Z',
    recallStrength: 68,
    attempts: 4,
    correctAnswers: 3,
    consecutiveCorrect: 1,
    mistakesCount: 1,
    notes: 'Remember: Timeline view isolates Main Thread vs Render Thread stalls. Always connect over ADB with Development Build + Autoconnect Profiler.'
  },
  {
    conceptId: 'concept-openxr-architecture',
    subjectId: 'xr-qa',
    status: 'needs_review',
    progress: 65,
    understandingLevel: 'intermediate',
    lastStudiedDate: '2026-09-20T10:15:00.000Z',
    lastPracticedDate: '2026-09-20T11:00:00.000Z',
    recallStrength: 45,
    attempts: 3,
    correctAnswers: 1,
    consecutiveCorrect: 0,
    mistakesCount: 2,
    notes: 'OpenXR decouples engine app from hardware runtimes (Oculus, SteamVR, WMR). Check Feature Groups in Unity project settings.'
  },
  {
    conceptId: 'concept-xr-grab-interactable',
    subjectId: 'xr-qa',
    status: 'practicing',
    progress: 42,
    understandingLevel: 'intermediate',
    lastStudiedDate: '2026-09-22T09:00:00.000Z',
    lastPracticedDate: '2026-09-23T11:30:00.000Z',
    recallStrength: 42,
    attempts: 5,
    correctAnswers: 2,
    consecutiveCorrect: 0,
    mistakesCount: 3,
    notes: 'Attach transforms dictate physical hand alignment. Velocity tracking mode needed for dynamic physics response.'
  },
  {
    conceptId: 'concept-cpu-gpu-bottlenecks',
    subjectId: 'xr-qa',
    status: 'learning',
    progress: 48,
    understandingLevel: 'intermediate',
    lastStudiedDate: '2026-09-21T15:20:00.000Z',
    lastPracticedDate: '2026-09-22T17:40:00.000Z',
    recallStrength: 48,
    attempts: 4,
    correctAnswers: 2,
    consecutiveCorrect: 0,
    mistakesCount: 2,
    notes: 'Rule of thumb: Lower eye texture resolution. If frame time drops, it is GPU fill-rate bound; if frame time stays flat, it is CPU main thread or draw call bound.'
  },
  {
    conceptId: 'concept-adb-commands',
    subjectId: 'xr-qa',
    status: 'practicing',
    progress: 37,
    understandingLevel: 'beginner',
    lastStudiedDate: '2026-09-19T18:10:00.000Z',
    lastPracticedDate: '2026-09-20T19:00:00.000Z',
    recallStrength: 37,
    attempts: 6,
    correctAnswers: 2,
    consecutiveCorrect: 0,
    mistakesCount: 4,
    notes: 'Key commands: adb devices, adb install -r, adb logcat -s Unity ActivityManager, adb shell, adb pull/push.'
  },
  {
    conceptId: 'concept-xr-origin',
    subjectId: 'xr-qa',
    status: 'learned',
    progress: 100,
    understandingLevel: 'intermediate',
    lastStudiedDate: '2026-09-23T10:00:00.000Z',
    lastPracticedDate: '2026-09-23T10:30:00.000Z',
    recallStrength: 85,
    attempts: 4,
    correctAnswers: 4,
    consecutiveCorrect: 4,
    mistakesCount: 0,
    notes: 'Never animate the XR Camera directly; always move the XR Origin rig transform.'
  },
  {
    conceptId: 'concept-3dof-6dof',
    subjectId: 'xr-qa',
    status: 'learned',
    progress: 100,
    understandingLevel: 'beginner',
    lastStudiedDate: '2026-09-22T11:00:00.000Z',
    lastPracticedDate: '2026-09-22T11:30:00.000Z',
    recallStrength: 92,
    attempts: 3,
    correctAnswers: 3,
    consecutiveCorrect: 3,
    mistakesCount: 0,
    notes: '3DoF is orientation only. 6DoF is orientation + position in space. Headsets dropping to 3DoF must pause rendering immediately.'
  },
  {
    conceptId: 'concept-sdlc-stlc',
    subjectId: 'xr-qa',
    status: 'learned',
    progress: 100,
    understandingLevel: 'beginner',
    lastStudiedDate: '2026-09-21T09:00:00.000Z',
    lastPracticedDate: '2026-09-21T09:30:00.000Z',
    recallStrength: 90,
    attempts: 3,
    correctAnswers: 3,
    consecutiveCorrect: 3,
    mistakesCount: 0,
    notes: 'STLC in XR must incorporate physical room boundaries, headset thermals, and sensor calibration.'
  },
  {
    conceptId: 'concept-smoke-sanity',
    subjectId: 'xr-qa',
    status: 'learned',
    progress: 100,
    understandingLevel: 'beginner',
    lastStudiedDate: '2026-09-22T14:00:00.000Z',
    lastPracticedDate: '2026-09-22T14:20:00.000Z',
    recallStrength: 88,
    attempts: 2,
    correctAnswers: 2,
    consecutiveCorrect: 2,
    mistakesCount: 0,
    notes: 'Headset smoke test gates deployment: boot, stereoscopic rendering without crash, 6DoF controller binding.'
  },
  {
    conceptId: 'concept-performance-fps-frametime',
    subjectId: 'xr-qa',
    status: 'learned',
    progress: 95,
    understandingLevel: 'intermediate',
    lastStudiedDate: '2026-09-23T16:00:00.000Z',
    lastPracticedDate: '2026-09-23T16:45:00.000Z',
    recallStrength: 82,
    attempts: 5,
    correctAnswers: 4,
    consecutiveCorrect: 2,
    mistakesCount: 1,
    notes: 'Frame time budgets: 72Hz = 13.88ms, 90Hz = 11.11ms, 120Hz = 8.33ms. Measure 99th percentile frame spikes.'
  },
  {
    conceptId: 'concept-tracking-loss-recovery',
    subjectId: 'xr-qa',
    status: 'needs_review',
    progress: 55,
    understandingLevel: 'intermediate',
    lastStudiedDate: '2026-09-18T10:00:00.000Z',
    lastPracticedDate: '2026-09-18T11:00:00.000Z',
    recallStrength: 50,
    attempts: 3,
    correctAnswers: 1,
    consecutiveCorrect: 0,
    mistakesCount: 2,
    notes: 'Test rapid camera occlusion: application must pause or blur rather than snapping rotation violently.'
  }
];
